server:
  port: 8085

spring:
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/imdb
    username: lobox
    password: lobox
springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'